version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fatture"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-74s4h953ai9m"
s3_prefix = "fatture"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
